apiVersion: apps/v1
kind: Deployment
metadata:
  name: rps-microservice
  labels:
    app: rps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rps
  template:
    metadata:
      labels:
        app: rps
    spec:
      containers:
      - name: rps-container
        # The line below is what the GitHub Action will constantly update
        image: your-docker-user/rps-game:placeholder
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: rps-service
spec:
  selector:
    app: rps
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
